namespace GameControllerForZwift.Core
{
    public enum ControllerInput
    {
        A,
        B,
        X,
        Y,
        Menu,
        View,
        DPad_Up,
        DPad_Down,
        DPad_Left,
        DPad_Right,
        LeftBumper,
        LeftTrigger,
        LeftThumbstick_Click,
        LeftThumbstick_TiltLeft,
        LeftThumbstick_TiltRight,
        LeftThumbstick_TiltUp,
        LeftThumbstick_TiltDown,
        RightBumper,
        RightTrigger,
        RightThumbstick_Click,
        RightThumbstick_TiltLeft,
        RightThumbstick_TiltRight,
        RightThumbstick_TiltUp,
        RightThumbstick_TiltDown
    }
}
