<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.33.1" />
    <PackageReference Include="InTheHand.BluetoothLE" Version="4.0.37" />
    <PackageReference Include="InTheHand.Net.Bluetooth" Version="4.1.44" />
    <PackageReference Include="Makaretu.Dns" Version="2.0.1" />
    <PackageReference Include="Makaretu.Dns.Multicast.New" Version="0.38.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />
    <PackageReference Include="Tmds.MDns" Version="0.8.0" />
    <PackageReference Include="Zeroconf" Version="3.7.16" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Makaretu\" />
  </ItemGroup>

</Project>
