namespace GameControllerForZwift.Core
{
    public enum ControllerInput
    {
        A,
        B,
        X,
        Y,
        Menu,
        View,
        DPadUp,
        DPadDown,
        DPadLeft,
        DPadRight,
        LeftBumper,
        RightBumper,
        LeftThumbstick,
        RightThumbstick,
        LeftThumbstickLeft,
        LeftThumbstickRight,
        LeftThumbstickUp,
        LeftThumbstickDown,
        LeftTrigger,
        RightThumbstickLeft,
        RightThumbstickRight,
        RightThumbstickUp,
        RightThumbstickDown,
        RightTrigger
    }
}
