name: Build, Test, and Deploy Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-test-deploy:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Extract version from .csproj 
      id: get_version 
      shell: pwsh 
      run:  | 
        $version = (Select-String -Path src/Presentation/GameControllerForZwift.WPF/GameControllerForZwift.WPF.csproj -Pattern '<Version>(.*?)</Version>').Matches.Groups[1].Value 
        echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

    # Framework-Dependent Build
    - name: Publish Framework-Dependent Build
      run: |
        mkdir ./artifacts/framework-dependent
        dotnet publish GameControllerForZwift_TestsExcluded.slnf -c Release -o ./artifacts/framework-dependent
        Get-ChildItem ./artifacts/framework-dependent -Recurse | Where-Object { $_.Extension -ne ".pdb" } | Compress-Archive -DestinationPath ./artifacts/gamecontrollerforzwift.zip

    # Self-Contained Build
    # - name: Publish Self-Contained Build
    #   run: |
    #     mkdir ./artifacts/self-contained
    #     dotnet publish GameControllerForZwift_TestsExcluded.slnf -c Release -r win-x64 --self-contained true -o ./artifacts/self-contained
    #     Compress-Archive -Path ./artifacts/self-contained/* -DestinationPath ./artifacts/gamecontrollerforzwift_with_runtime.zip

        
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 'v${{ env.VERSION }}' 
        release_name: 'Release v${{ env.VERSION }}' 
        draft: false 
        prerelease: false
    
    # Upload Framework-Dependent Build
    - name: Upload Framework-Dependent Build
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/gamecontrollerforzwift.zip
        asset_name: gamecontrollerforzwift.zip
        asset_content_type: application/zip

    # Upload Self-Contained Build
    # - name: Upload Self-Contained Build
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./artifacts/gamecontrollerforzwift_with_runtime.zip
    #     asset_name: gamecontrollerforzwift_with_runtime.zip
    #     asset_content_type: application/zip
