name: CI Workflow

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  get-the-version:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.result }} # Export step output to the job level

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Extract version from .csproj 
      id: get_version 
      shell: pwsh 
      run:  | 
        $version = (Select-String -Path src/Presentation/GameControllerForZwift.WPF/GameControllerForZwift.WPF.csproj -Pattern '<Version>(.*?)</Version>').Matches.Groups[1].Value 
        echo "Extracted version: $version" # Debugging the extracted value
        echo $version >> $env:GITHUB_OUTPUT

    - name: Debug Step Output
      run: |
        echo "Version is: ${{ steps.get_version.outputs.result }}"

  read-the-version:
    runs-on: ubuntu-latest
    needs: get-the-version

    steps:
    - name: Read version - no quotes
      run: |
        echo "Version from get-the-version: ${{ needs.get-the-version.outputs.version }}"
    
    - name: Read version - use quotes
      run: |
        echo Version from get-the-version: ${{ needs.get-the-version.outputs.version }}
