name: CI Workflow

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  get-the-version:
    name: Publish Release
    runs-on: windows-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Extract version from .csproj 
      id: get_version 
      shell: pwsh 
      run:  | 
        $version = (Select-String -Path src/Presentation/GameControllerForZwift.WPF/GameControllerForZwift.WPF.csproj -Pattern '<Version>(.*?)</Version>').Matches.Groups[1].Value 
        Write-Output $version
        echo "version=$version" >> "$GITHUB_OUTPUT"

    - name: Debug Job Output
      run: |
        echo "Version is: ${{ steps.get_version.outputs.version }}"

  read-the-version:
    name: Deploy Release to GitHub
    runs-on: ubuntu-latest
    needs: get-the-version

    steps:
    - name: Read version - no quotes
      run: |
        echo "Version from publish-framework: ${{ needs.publish-framework.outputs.version }}"
    
    - name: Read version - use quotes
      run: |
        echo Version from publish-framework: ${{ needs.publish-framework.outputs.version }}
