name: CI Workflow

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  checks: write
  security-events: write

jobs:
  test:
    name: Run Tests with Coverage
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 

    # These steps are required to run Appium tests on Windows
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # or the version you need

    - name: Install Appium
      run: |
        npm install -g appium
        appium driver install --source=npm appium-windows-driver

    - name: Download WinAppDriver
      run: |
        Invoke-WebRequest -Uri https://github.com/microsoft/WinAppDriver/releases/download/v1.2.1/WindowsApplicationDriver_1.2.1.msi -OutFile WinAppDriver.msi
        Start-Process msiexec.exe -ArgumentList '/i WinAppDriver.msi /quiet /norestart' -Wait

    - name: Set runner resolution to modern device size
      run: |
        Set-DisplayResolution -Width 1920 -Height 1080 -Force

    # - name: Start WinAppDriver
    #   run: |
    #     Start-Process -NoNewWindow -FilePath "C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe"
    - name: Start Appium Server
      shell: bash  
      run: |
        appium --allow-cors &

    # Prepare for .NET project
    - name: Restore dependencies
      run: dotnet restore

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'csharp'

    - name: Build solution
      id: build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal \
        --logger "trx;LogFileName=TestResults.trx" \
        --collect:"XPlat Code Coverage" \
        --results-directory:TestResults
      continue-on-error: true

    - name: Report Test Results
      uses: dorny/test-reporter@v1
      continue-on-error: true
      with:
        name: Test Results
        path: "**/TestResults.trx"
        reporter: dotnet-trx
        fail-on-error: 'true'

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      run: reportgenerator -reports:TestResults/**/coverage.cobertura.xml -targetdir:TestResults/CoverageReport -reporttypes:"HtmlInline_AzurePipelines;Cobertura"

    - name: Upload coverage to CodeCov
      uses: codecov/codecov-action@v5
      with:
        files: ${{ github.workspace }}\TestResults\CoverageReport\Cobertura.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      if: steps.build.outcome == 'success'

    - name: Extract version from .csproj
      id: get_version
      shell: pwsh
      run: |
        $version = (Select-String -Path src/Presentation/GameControllerForZwift/GameControllerForZwift.csproj -Pattern '<Version>(.*?)</Version>').Matches.Groups[1].Value
        echo "version=$version" >> $env:GITHUB_OUTPUT

    - name: Check if tag for version exists (only for main)
      if: github.event.pull_request.base.ref == 'main'
      id: check_tag
      shell: pwsh
      run: |
        $version = 'v${{ steps.get_version.outputs.version }}'
        $tagExists = git tag --list | Where-Object { $_ -eq $version }
        if ($tagExists) {
          Write-Host "Tag already exists. $version is not a new app version."
          echo "tag_exists=true" >> $env:GITHUB_ENV
        } else {
          Write-Host "Tag does not exist. $version is a new app version."
          echo "tag_exists=false" >> $env:GITHUB_ENV
        }

    - name: Report Check as Status
      if: github.event.pull_request.base.ref == 'main'
      uses: actions/github-script@v6
      with:
        script: |
          const tagExists = process.env.tag_exists === 'true';
          
          const conclusion = tagExists ? 'failure' : 'success';
          const summary = tagExists
            ? `Version v${{ steps.get_version.outputs.version }} already exists.`
            : `New app version v${{ steps.get_version.outputs.version }}.`;
          const message = tagExists
            ? `There is already a tag and Release for version \`v${{ steps.get_version.outputs.version }}\`. Please update the version number in the application project file.`
            : `Merging to \`main\` will create a new tag and release for version \`v${{ steps.get_version.outputs.version }}\`.`;

          await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: "Version Check",
            head_sha: context.payload.pull_request.head.sha,
            status: "completed",
            conclusion: conclusion,
            output: {
              title: summary,
              summary: message,
            },
          });