name: Build, Test, and Analyze

on:
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  security-events: write

jobs:
  # ------------------------
  # 1. Build Job
  # ------------------------
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          **/bin/Release
          **/obj

  # ------------------------
  # 2. Test Job
  # ------------------------
  test:
    runs-on: windows-latest
    needs: build  # Wait for the build job to complete

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: .

    - name: Run tests with XPlat Code Coverage
      run: |
        dotnet test --configuration Release --no-build --verbosity normal \
          --collect:"XPlat Code Coverage" \
          --results-directory:TestResults

    - name: Install ReportGenerator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate Coverage Report
      run: |
        reportgenerator -reports:TestResults/**/coverage.cobertura.xml \
                        -targetdir:TestResults/coverage-report \
                        -reporttypes:"HtmlInline_AzurePipelines;Cobertura"

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: TestResults/coverage-report

  # ------------------------
  # 3. CodeQL Analysis Job
  # ------------------------
  analyze:
    runs-on: windows-latest
    needs: build  # Wait for the build job to complete

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'csharp'

    - name: Build solution for CodeQL
      run: dotnet build --configuration Release --no-restore

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

  # ------------------------
  # 4. Report Job
  # ------------------------
  report:
    runs-on: windows-latest
    needs: [test]  # Wait for the test job to complete

    steps:
    - name: Download Coverage Report
      uses: actions/download-artifact@v3
      with:
        name: coverage-report
        path: TestResults/coverage-report

    - name: Post Coverage Summary to PR
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: TestResults/coverage-report/Cobertura.xml
        format: markdown
        output: both